ACS Variable Categories

HOUSING VARIABLES
  
  ACREAGE (CUERDA)
  CONDOMINIUM STATUS AND FEE
  GROSS RENT
  GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME
  HOMEOWNER VACANCY RATE
  HOUSEHOLD SIZE
  HOUSING UNIT
  INSURANCE FOR FIRE, HAZARD, AND FLOOD
  MONTHLY HOUSING COSTS
  MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME
  MORTGAGE PAYMENT
  MORTGAGE STATUS
  OCCUPANTS PER ROOM
  OCCUPIED HOUSING UNITS 
  OWNER-OCCUPIED UNITS
  POPULATION IN OCCUPIED HOUSING UNITS
  POVERTY STATUS OF HOUSEHOLDS
  RENTAL VACANCY RATE
  SPECIFIED OWNER-OCCUPIED AND VACANT-FOR-SALE UNITS
  SPECIFIED RENTER-OCCUPIED AND VACANT-FOR-RENT UNITS
  TENURE
  UNITS IN STRUCTURE
  UTILITY COSTS
  VACANCY STATUS
  VACANT – CURRENT RESIDENCE ELSEWHERE
  VACANT HOUSING UNITS
  VALUE
  VEHICLES AVAILABLE
  YEAR HOUSEHOLDER MOVED INTO UNIT
  YEAR STRUCTURE BUILT

POPULATION VARIABLES

  AGE 
  EDUCATIONAL ATTAINMENT
  EMPLOYMENT STATUS 
  HEALTH INSURANCE COVERAGE 
  HISPANIC OR LATINO ORIGIN
  HOUSEHOLD 
  HOUSEHOLD TYPE AND RELATIONSHIP
  HOUSEHOLD SIZE
  HOUSEHOLDER
  INCOME IN THE PAST 12 MONTHS
  LABOR FORCE STATUS
  MEANS OF TRANSPORTATION TO WORK
  OCCUPATION
  PERSONS IN FAMILY
  PERSONS IN HOUSEHOLD
  PLACE OF WORK 
  POVERTY STATUS IN THE PAST 12 MONTHS 
  PRIVATE VEHICLE OCCUPANCY 
  RACE
  SCHOOL ENROLLMENT AND TYPE OF SCHOOL
  TYPE OF SCHOOL 
  USUAL HOURS WORKED IN THE PAST 12 MONTHS 
  WEEKS WORKED IN THE PAST 12 MONTHS 
  WORK EXPERIENCE 
  WORK STATUS IN THE PAST 12 MONTHS 
  
  
                                                                                                                                                   
  [23] "POVERTY STATUS IN THE PAST 12 MONTHS OF INDIVIDUALS BY SEX BY EDUCATIONAL ATTAINMENT"                                                                                                                    
  [25] "POVERTY STATUS IN THE PAST 12 MONTHS OF INDIVIDUALS BY SEX BY EMPLOYMENT STATUS"                                                                                                                         
  [43] "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY WORK EXPERIENCE OF HOUSEHOLDER AND SPOUSE"                                                                                            
  [45] "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY HOUSEHOLD TYPE BY EDUCATIONAL ATTAINMENT OF HOUSEHOLDER"                                                                                             
  [46] "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY HOUSEHOLD TYPE BY TENURE"                                                                                                                            
  [47] "POVERTY STATUS IN THE PAST 12 MONTHS BY AGE"
  [57] "POVERTY STATUS OF INDIVIDUALS IN THE PAST 12 MONTHS BY LIVING ARRANGEMENT"             
  
  5
  C17002_001
  Estimate!!Total:
    RATIO OF INCOME TO POVERTY LEVEL IN THE PAST 12 MONTHS
  286
  C17002_002
  Estimate!!Total:!!Under .50
  RATIO OF INCOME TO POVERTY LEVEL IN THE PAST 12 MONTHS
  287
  C17002_003
  Estimate!!Total:!!.50 to .99
  RATIO OF INCOME TO POVERTY LEVEL IN THE PAST 12 MONTHS
  288
  C17002_004
  Estimate!!Total:!!1.00 to 1.24
  RATIO OF INCOME TO POVERTY LEVEL IN THE PAST 12 MONTHS
  289
  C17002_005
  Estimate!!Total:!!1.25 to 1.49
  RATIO OF INCOME TO POVERTY LEVEL IN THE PAST 12 MONTHS
  290
  C17002_006
  Estimate!!Total:!!1.50 to 1.84
  RATIO OF INCOME TO POVERTY LEVEL IN THE PAST 12 MONTHS
  291
  C17002_007
  Estimate!!Total:!!1.85 to 1.99
  RATIO OF INCOME TO POVERTY LEVEL IN THE PAST 12 MONTHS
  292
  C17002_008
  
  
  
  
'B15003_022', # Estimate!!Total:!!Bachelor's degree
'B15003_023', # Estimate!!Total:!!Master's degree
'B15003_024', # Estimate!!Total:!!Professional school degree
'B15003_025', # Estimate!!Total:!!Doctorate degree