ACS Variable Categories

HOUSING VARIABLES
  
  ACREAGE (CUERDA)
  CONDOMINIUM STATUS AND FEE
  GROSS RENT
  GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME
  HOMEOWNER VACANCY RATE
  HOUSEHOLD SIZE
  HOUSING UNIT
  INSURANCE FOR FIRE, HAZARD, AND FLOOD
  MONTHLY HOUSING COSTS
  MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME
  MORTGAGE PAYMENT
  MORTGAGE STATUS
  OCCUPANTS PER ROOM
  OCCUPIED HOUSING UNITS 
  OWNER-OCCUPIED UNITS
  POPULATION IN OCCUPIED HOUSING UNITS
  POVERTY STATUS OF HOUSEHOLDS
  RENTAL VACANCY RATE
  SPECIFIED OWNER-OCCUPIED AND VACANT-FOR-SALE UNITS
  SPECIFIED RENTER-OCCUPIED AND VACANT-FOR-RENT UNITS
  TENURE
  UNITS IN STRUCTURE
  UTILITY COSTS
  VACANCY STATUS
  VACANT – CURRENT RESIDENCE ELSEWHERE
  VACANT HOUSING UNITS
  VALUE
  VEHICLES AVAILABLE
  YEAR HOUSEHOLDER MOVED INTO UNIT
  YEAR STRUCTURE BUILT

POPULATION VARIABLES

  AGE 
  EDUCATIONAL ATTAINMENT
  EMPLOYMENT STATUS 
  HEALTH INSURANCE COVERAGE 
  HISPANIC OR LATINO ORIGIN
  HOUSEHOLD 
  HOUSEHOLD TYPE AND RELATIONSHIP
  HOUSEHOLD SIZE
  HOUSEHOLDER
  INCOME IN THE PAST 12 MONTHS
  LABOR FORCE STATUS
  MEANS OF TRANSPORTATION TO WORK
  OCCUPATION
  PERSONS IN FAMILY
  PERSONS IN HOUSEHOLD
  PLACE OF WORK 
  POVERTY STATUS IN THE PAST 12 MONTHS 
  PRIVATE VEHICLE OCCUPANCY 
  RACE
  SCHOOL ENROLLMENT AND TYPE OF SCHOOL
  TYPE OF SCHOOL 
  USUAL HOURS WORKED IN THE PAST 12 MONTHS 
  WEEKS WORKED IN THE PAST 12 MONTHS 
  WORK EXPERIENCE 
  WORK STATUS IN THE PAST 12 MONTHS 
