

7. Generalizability [Simplify term, maybe in question form?]

```{r Generalizability Demographic, echo= F, warning=F, error=F, message=F}

# 7. GENERALIZABILITY TEST

# Replace with NEW INCOME DATA
incomeTest <- blocks %>%
  select(
         PCTHHMI000,
         PCTHHMI010,
         PCTHHMI015,
         PCTHHMI020,
         PCTHHMI025,
         PCTHHMI030,
         PCTHHMI035,
         PCTHHMI040,
         PCTHHMI045,
         PCTHHMI050,
         PCTHHMI060,
         PCTHHMI075,
         PCTHHMI100,
         PCTHHMI125,
         PCTHHMI150,
         PCTHHMI200
         ) %>%
  mutate(lowIncome =
           PCTHHMI000+
           PCTHHMI010+
           PCTHHMI015+
           PCTHHMI020+
           PCTHHMI025+
           PCTHHMI030+
           PCTHHMI035+
           PCTHHMI040+
           PCTHHMI045+
           PCTHHMI050+
           PCTHHMI060+
           PCTHHMI075,
         highIncome=
           PCTHHMI100,
           PCTHHMI125,
           PCTHHMI150,
           PCTHHMI200) %>%
  mutate(incomeContext = ifelse((lowIncome) > .5, "Low Income", "High Income")) %>%
  select(-starts_with('PCTHHMI'), -lowIncome, -highIncome)


# Plot the income groups division
grid.arrange(ncol = 1,
  ggplot() + geom_sf(data = na.omit(incomeTest), aes(fill = incomeContext)) +
    scale_fill_manual(values = c(palette5[4], palette5[3], palette5[2]), name="Income Context") +
    #scale_discrete(limits=dat$V1) +
    labs(title = "Income Context") +
    mapTheme() + theme(legend.position="bottom"))


```


```{r Generalizabiliy test table, echo= F, warning=F, error=F, message=F}

st_join(bothRegressions, incomeTest) %>% 
  group_by(Regression, incomeContext) %>%
  summarize(mean.MAPE = scales::percent(mean(price.APE, na.rm = T))) %>%
  st_drop_geometry() %>%
  spread(incomeContext, mean.MAPE) %>%
  kable(caption = "Test set MAPE by household income context") %>% kable_styling()

```

